### PR TITLE
Feature Request #3472

### PR DESCRIPTION
**Pull request by wtravO**
** >> Make sure you describe your PR to the README Change Log section! << **
This PR references Issue #3472 
This PR changes (delete as applicable)

* Documentation
* TypeScript Defs
* The public-facing API

Describe the changes below:
This PR will add a kerning property to BitmapText that allows developers to add additional spacing between characters.  Default val is 0.

### CODE REVIEW

**Comment by photonstorm** [comment]
I like this, but I wonder if it's the wrong property name to use. Because `kerning` values are already specified inside the Bitmap Text data files and applied during rendering. You can see them extracted in `ParseXMLBitmapFont.js` and used in the renderer.

**Comment by wtravO** [comment]
Yeah, I was thinking about that as well. Perhaps `charPadding`?

**Comment by harriscory730** [comment]
So Mr Richard what's is next

**Comment by wtravO** [comment]
I believe I had Kerning confused with Letter Spacing in this scenario.  So, in this case, I believe it should be named `letterSpacing`.  Should avoid confusion and match up better to common typography terminology.

Referencing this article : https://graphicdesign.stackexchange.com/questions/2606/difference-between-kerning-vs-letter-spacing

**Comment by photonstorm** [comment]
`letterSpacing` is much better, thanks.

**Comment by wtravO** [comment]
It's just when I created the branch. :) Had multiple PR's in at the same time.

**Comment by wtravO** [comment]
Not sure what happened there.  It pulled the creation of the branch in as a commit it seems?  Can be reverted and squashed perhaps.  Should fix it.

**Pull request merged**
