### PR TITLE
Add quadraticBezier to API

### PR DESCRIPTION
**Pull request by RiCoTeRoX**
Curves.QuadraticBezier

Description
- Add QuadraticBezier to Curve API

### CODE REVIEW

**Comment by Affi12** [comment]
Hey

**Comment by sibelku** [comment]
?

Affi12 <notifications@github.com> schrieb am Sa. 3. März 2018 um 09:04:

**Comment by Affi12** [comment]
I'm New here just some tips for me dear

**Comment by photonstorm** [comment]
Nice one, let's get this in. I'll have to modify the `@since` values but that's all.

**Comment by photonstorm** [comment]
Have added it to the Path class too.

**Pull request merged**
