### PR TITLE
On Ceiling Method Addition

### PR DESCRIPTION
**Pull request by yigitozdemir**
Hi Guys,

I found out, there is a shortcut for controlling on floor but there is no shortcut for onCeiling control, i tought it might be useful to implement a same way for controlling if body collides ceiling or not.

### CODE REVIEW

**Comment by yigitozdemir** [comment]
Today i asked about how to use grunt and tested my code with

```javascript
if(this.activeSprite.body.onFloor() | this.activeSprite.body.onCeiling() ){
        this.changeSprite("dead");
}
```

And its working. I tought if there is a function to control is body onFloor, there should be a function to control is body onCeiling.

**Comment by pnstickne** [comment]
Make sure the jsdoc is correct, including the method name.

Curious question: why not just using `.blocked.up` directly?

**Comment by Garbanas** [comment]
@pnstickne `.blocked.down|up` only works for TileMaps but not for other Arcade bodies - you'd have to check with `touching` or `wasTouching`, although these values change with every single collision if I remember correctly.

**Comment by photonstorm** [comment]
This may be old, but why not.

**Pull request merged**
