### PR TITLE
Get ascent and descent from context.measureText method

### PR DESCRIPTION
**Pull request by rexrainbow**
This PR (delete as applicable)

* Improve performance

Describe the changes below:

Get ascent and descent from context.measureText method instead of scanning image data. ( #5261 )

### CODE REVIEW

**Comment by rexrainbow** [comment]
It is fine to reject this PR for v4 benefit.

**Comment by photonstorm** [comment]
On reflection, I'm happy to merge this in, but I can't have it replace the old way of doing it, as the new one doesn't work on any version of IE. So I think it'll need a conditional to check if it's supported first.

**Comment by rexrainbow** [comment]
Original solution added, for IE and Firefox for Android which do not have `actualBoundingBoxAscent` and `actualBoundingBoxDescent` properties. Thanks for this advice.

**Comment by photonstorm** [comment]
Thanks for the update.

**Pull request merged**
