### PR TITLE
Particles: Fixed an issue where particle systems held onto emitters b…

### PR DESCRIPTION
**Pull request by hilts-vaughan**
Important: Pull Requests should only be issued against the dev branch. PRs against the master branch will always be closed.

Nothing, it's a bug fix
Describe the changes below:

Fixes: #2851

Instead of using name to track things, we should just track by internal ID. I have confirmed it fixes the issue.

### CODE REVIEW

**Comment by hilts-vaughan** [comment]
I'm looking into fixing these. It looks like rebase didn't follow the movie as I'd hoped...

**Comment by hilts-vaughan** [comment]
All should be fixed.

**Comment by photonstorm** [comment]
Thanks - correct folder now :)

**Comment by hilts-vaughan** [comment]
Thanks Rich!

**Pull request merged**
