### PR TITLE
doc improvement & minor bug fix

### PR DESCRIPTION
**Pull request by jcyuan**
√ Updates the Documentation
1, mainly for Structs.List / Map / Set: provide type for the callback's argument
2, remove comment for the $type fields in List.js to avoid jsdoc warning while building

x Adds a new feature

√ Fixes a bug (fixed in master branch 7ee0a71)
~~1, List.js -> getFirst: ArrayUtils.GetFirstElement changed to ArrayUtils.GetFirst~~
~~2, Container.js -> same as List.js~~

the new .d.ts file was passed the test
image

### CODE REVIEW

**Comment by jcyuan** [comment]
ah, once merge from master the bug disappears for List.js, the still exists in Container.js

**Comment by photonstorm** [comment]
It was fixed in both: 
https://github.com/photonstorm/phaser/commit/7ee0a717f5095a1a917cb54ce9570b528fbe43d4

So please make sure you’ve merged correctly.

**Comment by jcyuan** [comment]
@photonstorm yes you are right, at last step I merged from master into my branch so in "Files Changed" of this PR there are only doc changes.
I'll delete my branch and re-fork again after this PR.

**Comment by photonstorm** [comment]
👍

**Pull request merged**
