### PR TITLE
WebRTC didn't work with GameObject.Video, so I made GameObject.VideoStream

### PR DESCRIPTION
**Pull request by landongn**
Howdy! I've been working on a project that involves webRTC style livestream calling, and while `GameObject.Video` has been fine for static content (e.g; loaded through `game.load.video`), it did not work that well when it came to using `MediaStream` DOM objects, which are sort of like a 'ticket' to a livestream on a remote server. 

Anyway, preamble; Here's what's in this PR: 

- added Factory and Creator for `GameObject.VideoStream`, derived from `GameObject.Video`'s implementation. 
- cloned and modified the `GameObject.Video` implementation into `GameObject.VideoStream`. 
- while `Video` has a `loadURL` method for changing media, this applies primarily with static content (e.g; something that 1. is a string and 2. ends in .mp4, .webm, etc), thus `VideoStream` provides the `loadMediaStream` method, which allows callers to pass in a functional RTC video element for use as the texture source. 

the same api applies for calling `scene.add.video` as `scene.add.videostream` 

These implementations are functional now, though do not have any appropriate tests as this is, so far, an implementation detail I have going in my fork, and was curious if this implementation was missing anything for landing upstream. 

Thanks for this library!

### CODE REVIEW

**Comment by photonstorm** [comment]
This pull request has been mentioned on **Phaser**. There might be relevant details there:

https://phaser.discourse.group/t/webrtc-and-phaser/6053/3

**Comment by paulsymphony** [comment]
Can you provide a quick example of this working with getUserMedia? I'm unsure of how to implement.

**Comment by landongn** [comment]
Sure.  The basic idea is the same, you create a video object via `scene.add.video` or directly (and add it to your scene), and when you have the returned promise from `getUserMedia`, the thing you get back is a `mediaStream`, which can be applied directly to the video object. 

```javascript
async function getMedia(constraints) {
  let stream = null;

  try {
    stream = await navigator.mediaDevices.getUserMedia(constraints);
    /* use the stream */
  } catch(err) {
    /* handle the error */
  }
}
```  that `stream` object there can be set as the video's `srcObject`, giving you a video element with live video from the users camera. pass that to `loadMediaStream` of the `VideoStream` object you added, and voila, you've got video.

**Comment by paulsymphony** [comment]
Thank you - I know how to use getUserMedia, and have a demo in straight HTML / JS working. In phaser, I'm confused at how to use the 'stream' above. Here's what I have when the getUserMedia() call is successful above:

    private handleSuccess(stream) {
        console.log("successfully connected to camera:" , stream)
        console.log('Got stream with constraints:', this.constraints);

        this.videoObj = this.targetScene.add.video(400,300,'');
        this.videoObj.srcObject = stream;
        this.videoObj.play(true);
    }

But nothing ever shows up onscreen...

**Comment by photonstorm** [comment]
@landongn thanks for this PR - I do wonder if it wouldn't be better to just merge the capability into the existing Video object? It doesn't look like it would add all that much to it (vs. having a whole new object)

**Comment by paulsymphony** [comment]
WebRTC is amazing, and has so many possibilities when combined w/ Phaser. Adding web conferencing and screen sharing is becoming a huge deal. I'm willing to help if I can. Thanks to you both!

**Comment by paulsymphony** [comment]
@landongn I have tried a lot of options, but still am getting errors when I try to connect the stram to the VideoStream object. Can you provide the code (probably only a few lines) of how to create the video / videostream objects and use the 'stream' from the getUserMedia() ?

**Comment by landongn** [comment]
> @landongn thanks for this PR - I do wonder if it wouldn't be better to just merge the capability into the existing Video object? It doesn't look like it would add all that much to it (vs. having a whole new object)

@photonstorm yeah, you're likely correct; i wanted to add the functionality with the least mutation to the existing video object for the sake of being a good neighbor; the only material changes are to how it handles loading media depending on the kind of media, which livestreams is a new addition to the ones put into the loader caches and so on. 

@paulsymphony please view the code for `VideoObject.loadMediaStream` -- once you have a stream ready to be set, just send it to that method and the video element should work just as it does in the normal browser world. I can't help much more without some idea of your scene graph and how you're handling the video elements used for playback.

**Comment by landongn** [comment]
I'll close this to revise and open a new PR once it's tested out.

**Comment by MatthewPringle** [comment]
@landongn thought I recognised you from the ember add-on you did. What are you using for WebRTC. At the moment I'm using peerjs which seems to be a good package, but it is quite old and not exactly bug free.

**Comment by wafflekat** [comment]
@landongn 
I'm really interested in this feature for a project that depends on built in webrtc video communication. Is there any progress on the new PR?

Cheers!

**Comment by landongn** [comment]
Hey there all, so I've unfortunately abandoned this approach and I didn't end up making the PR.  However, here's the long and short of it: 

```javascript
    loadMediaStream: function (videoElement)
    {

        if (this.videoTexture)
        {
            this.scene.sys.textures.remove(this._key);
        }
        this.is_ready = true;
        this.video = videoElement;
        this.video.play();
        return this;
    },
```

In a nutshell; add this function to a local subclass of `Video`, and as use `videoElement` to directly set the video asset of the stream.  Just pass a configured and ready video DOM element to the method there, and bobs your uncle, it works.

**Comment by wafflekat** [comment]
Thanks! Unfortunately this solution has its own issues, primarily the inability to resize the video.. setDisplaySize errors out because of a null frame. 
It's a shame this hasn't been addressed properly yet.. hopefully someone takes the helm on this issue.

**Comment by wafflekat** [comment]
For anyone else who stumbles upon this, I managed to solve it this way
class VideoStream extends Phaser.GameObjects.Video
```typescript
    public loadMediaStream? = async (videoElement: HTMLVideoElement) => {

    this.video = videoElement;
    await this.video.play();
    if (this.videoTexture)
    {
      this.scene.sys.textures.remove(this._key);

      // @ts-ignore
      this.videoTexture = this.scene.sys.textures.create(this._key, videoElement, videoElement.videoWidth, videoElement.videoHeight);
      this.videoTextureSource = this.videoTexture.source[0];
      this.videoTexture.add('__BASE', 0, 0, 0, videoElement.videoWidth, videoElement.videoHeight);

      // @ts-ignore
      this.setTexture(this.videoTexture);
      // @ts-ignore
      this.setSizeToFrame();
      this.updateDisplayOrigin();

      // @ts-ignore
      this.emit(Phaser.Events.VIDEO_CREATED, this, videoElement.videoWidth, videoElement.videoHeight);
    }
    else
    {
      this.updateTexture();
    }
    return this;
  };
```

phaser.d.ts
```typescript 
declare namespace Phaser {
  namespace GameObjects {
    export interface Video {
      _key: any;
    }
  }
}
```

Sadly the type definition are very limiting in extending and customizing Phaser, so I had to resort to a lot of ts-ignores

**Comment by flodev** [comment]
Hi,
I got it working by using the video object only:

```javascript
  try {
    const constraints = {
      video: true,
      audio: true,
    };
    const mediaStream = await navigator.mediaDevices.getUserMedia(constraints);
    var video = document.createElement("video");
    video.playsinline = true;
    video.srcObject = mediaStream;
    video.width = 320;
    video.height = 240;
    video.autoplay = true;

    const phaserVideo = new Phaser.GameObjects.Video(this, 100, 100);
    phaserVideo.width = 320;
    phaserVideo.height = 240;
    phaserVideo.video = video;
    this.add.existing(phaserVideo);
  } catch (e) {
    console.log("error", e.message, e.name);
  }
```

**Pull request closed without merging**
