### PR TITLE
Bitmaptext: Add methods of GetBounds

### PR DESCRIPTION
**Pull request by rexrainbow**
This PR (delete as applicable)

* Adds a new feature

Describe the changes below:

Add methods of GetBounds into Bitmaptext game object.

### CODE REVIEW

**Comment by photonstorm** [comment]
I'm in two minds about this. While it makes sense for Static Bitmap Text, it will return incorrect results for Dynamic Bitmap Text (which extends Static, so will gain this component as well)

**Comment by rexrainbow** [comment]
@photonstorm You are right. There is no easy way to get bounds of all characters in Dynamic-Bitmaptext game object. 
- How about return null for all GetBounds method in Dynamic-Bitmaptext game object?
- Or just leave it for user, user could add ComputedSize and GetBounds methods manually.

**Comment by photonstorm** [comment]
The problem is that we won't be able to override the documentation that is generated for Dynamic BitmapText to make it known that `null` is what's being returned :(

**Comment by rexrainbow** [comment]
PR closed, since I don't have good solution either. :(

**Comment by rexrainbow** [comment]
Here is the sample code of injecting `getBounds` method manually.

```javascript
const Components = Phaser.GameObjects.Components;
Phaser.Class.mixin(
    Phaser.GameObjects.BitmapText,
    [
        Components.ComputedSize,
        Components.GetBounds
    ]
);
```

**Pull request closed without merging**
