### PR TITLE
Allow custom creation of response object

### PR DESCRIPTION
**Pull request by pnstickne**
Per https://github.com/photonstorm/phaser/issues/1591

A fairly-generic method of intercepting request creation and specifying custom request objects (and configurations therein). Works for XHR / Image / Audio as well as "fine tuning" the URL or whatnot.

Usage for custom XHR headers looks like:

    loader.onCreatingRequest.add(createRequest, this);

    function createRequest (loader, r)
    {
        if (r.requestType === 'xhr' && shouldCustomizeRequestForUrl(r.url))
        {
            var xhr = loader.createXMLHttpRequest(r.url);
            // any relevant modification to XHR / request can be done here
            // (including providing a fake proxy object or using a different URL entirely)
            // but there are some restrictions and the xhr.responseType will be overridden
            xhr.setRequestHeader('custom-header', 'value');
            r.requestObject = xhr;
        }
    }

### CODE REVIEW

**Comment by pnstickne** [comment]
"npm install" failed for Travis CI :<

**Comment by photonstorm** [comment]
How safe is this to merge this close to release? At least I've extensively tested the current 2.3 Loader through several large client projects, but I can see lots of underlying structure changes here.

**Comment by pnstickne** [comment]
I would say 'fairly safe'. Most of the structure changes come from unifying XDR+XHR code (of which I have sadly not tested for XDR, but XHR works as expected).

The building (and extraction of) the request configuration doesn't really affect the structure and semantic differences should only be observed _if_ adding an `onCreatingRequest` handler and altering the supplied values.

Some of the image/audio callback code is updated for consistency and I have not run into any regression cases.

**Comment by photonstorm** [comment]
I'm afraid I'm going to leave this one be. I'm happy with how the Loader currently works, and will leave features like this for Lazer.

**Pull request closed without merging**
