### PR TITLE
Button now has useHandCursor set to true by default

### PR DESCRIPTION
**Pull request by alamboley**
I don't see any reason why it isn't set to true by default... ?

### CODE REVIEW

**Comment by photonstorm** [comment]
Hmmm, I guess it could be. It's unnecessary on mobile though which is where Phaser is used most.

**Comment by alamboley** [comment]
Well, does it have any inpact on mobile performance? It shouldn't, and if it's the case, Phaser should not set it to true on mobile.

I'm on mobile web & desktop + CocoonJS, each time I create a button I've to add that damn line. Obviously, I can extend Button...

**Comment by photonstorm** [comment]
Ah what the hell, it's in 2.4.

**Comment by alamboley** [comment]
:+1:

**Pull request closed without merging**
