### PR TITLE
Fixed bug with docs TOC scrolling

### PR DESCRIPTION
**Pull request by rivertam**
Removed the shims on the major elements and changed the `scrollTo` target position to `the top of the target element - the height of the navbar*1.2`. Now scrolling is more consistent.

### CODE REVIEW

**Comment by Bilge** [comment]
:+1: Came here to report this bug.

**Comment by pnstickne** [comment]
@rivertam Thanks for the PR.

However, can you submit another one without all the changes to the docs themselves? (Just make the changes to the templates, but don't "add" changes to the docs/ directory.)

The docs can be generated locally for testing and are eventually generated for deployment, but shouldn't be committed unless a "release".

**Comment by rivertam** [comment]
@pnstickne I don't think I need to make a new PR. I just reverted the changes (because I never actually built the project). So I think this PR is updated with the reverts of the stuff that shouldn't have been done, simplifying the changes.

**Comment by photonstorm** [comment]
As it stands this merge request is just 2 files (the template and the less file), which looks perfectly safe for me to merge if you like (as long as that is all that's required?)

**Comment by pnstickne** [comment]
@rivertam That will work, thanks!

**Comment by rivertam** [comment]
Hey guys, sorry for being MIA. Been wrestling with Git, and I can't seem to get get grunt to compile the templates, but I'm fairly certain the last change is also safe, but it's the most important one. Sorry for so much commotion over such a small issue.

**Comment by Bilge** [comment]
It's actually a big issue. The docs are a royal pain in the ass to use right now.

**Comment by photonstorm** [comment]
Closing this one off as it's been addressed directly in the docstrap template repo, which I just merged the new toc.js file from today.

**Pull request closed without merging**
