### PR TITLE
Add ability to play animation reverse(#3837) and some comment to TextureManager.js

### PR DESCRIPTION
**Pull request by Edwin222**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Updates the Documentation
* Adds a new feature
* ~~Fixes a bug~~

Describe the changes below:

* Add a feature to play animations in reversed sequence (issue #3837)
I added a attribute `reverse` in `AnimationConfig`. default value is false. 
if reverse is true, that animation's sequence is reversed. it seems to works in my test case. Feedback please.

* Add some descriptions to TextureManager.js

### CODE REVIEW

**Comment by khaleb85** [comment]
I`m trying to solve this in a different way, you basically are reversing the frame orders, I am trying to create a **revert** function that can reverse the animation at any time, also a **playReverse** function that runs the animation in reverse mode.

I don´t know which solution is the best one  @photostorm can tell us?

**Comment by Edwin222** [comment]
I also thought about that. However, too many functions and classes are associated and all of that should be modifed to implement that way. It can cause many errors so I was trying to find a solution that doesn't have to touch original source code.

If you can implement that function safely, your solution will be better than mine.

**Comment by photonstorm** [comment]
Thanks for the PR @Edwin222 ! I think I'd rather do proper reversed animation support than just flipping the array. However, the comments you added into the Texture Manager are great so I'd like to merge those! Would you mind removing the reverse change, then I'll gladly pull in the rest. Every little bit helps when it comes to the docs!

**Comment by Edwin222** [comment]
Thank you for feedback. I change it.

**Comment by photonstorm** [comment]
Thank you :) Just to say that reverse animation support will be coming in 3.12!

**Pull request merged**
