### PR TITLE
fixed typescript def for ResizeCallback

### PR DESCRIPTION
**Pull request by rmartone**

### CODE REVIEW

**Comment by rmartone** [comment]
interface ResizeCallback {
        (scale: ScaleManager, parentBounds: Rectangle): any;
    }

**Comment by mikaturunen** [comment]
Would it be potentially viable options to give someone the rights to maintain the TS scripts? Personally I would love to do this as I'm huge fan of TypeScript. :+1: I've got some big typescript d.ts  file changes coming in too in a bit. Once I finish my issue track on phaser-examples-typescript.

If you don't feel comfortable giving someone the contribution rights here, how about dividing it into a sub-repo this repository depends on and give contribution rights to that sub-repo?

Just curious and would like to see some push on this front too (I'm aware that the TS support from the framework itself is dropped but would love to keep these up to date..).

**Comment by photonstorm** [comment]
The defs are kept up to date via lots of contributors. They all manage it via PRs and have done so for a good while now, so I intend to keep it that way to be honest. I doubt there are a big number of significant changes needed to the defs, but you're welcome to issue a PR if it fixes problems that exist in them currently.

**Comment by mikaturunen** [comment]
:+1: sounds good.

**Comment by rmartone** [comment]
Stumbled upon the faulty def when implementing scaleMode USER_SCALE for a typescript project.  Submitted an issue with the fix.  

Thanks for the amazing framework!

**Comment by photonstorm** [comment]
I can't merge this because it's against the wrong branch (all PRs to dev branch, always) - but have made the change locally in dev, so will close this one off.

**Pull request closed without merging**
