### PR TITLE
Add Phaser.Math.Angle.Random() and Phaser.Math.Angle.RandomDegrees()

### PR DESCRIPTION
**Pull request by samme**
This PR

* Adds a new feature

### CODE REVIEW

**Comment by KingCosmic** [comment]
there's alread a angle generator on Phaser.Math.RandomNumberGenerator.angle()

is there anything this does differently / couldn't just be some options for that function

**Comment by rexrainbow** [comment]
@KingCosmic They are different, RandomNumberGenerator is a [3rd party random number generator](https://github.com/photonstorm/phaser/blob/master/src/math/random-data-generator/RandomDataGenerator.js), with a *seed* parameter. New methods Angle.Random, and Angle.RandomDegrees uses[ built-in *random* method](https://github.com/photonstorm/phaser/blob/master/src/math/FloatBetween.js#L20), that would have better performance ideally. (But built-in random method can't assign seed)

**Comment by samme** [comment]
Should the range be [-π, π] instead of [0, 2π]? Opinions?

**Comment by photonstorm** [comment]
Merged and updated so the range is -180,180, as that is what Phaser uses internally.

**Pull request merged**
