### PR TITLE
Changelog updated, preparing for 2.7.1 update

### PR DESCRIPTION
**Pull request by stoneman1**
This PR changes (delete as applicable)

* Documentation (Changelog and Readme changelog)

Describe the changes below:
Updated changelog and readme

### CODE REVIEW

**Comment by photonstorm** [comment]
Let me know when you want 2.7.1 published to npm.

**Comment by stoneman1** [comment]
Probably best to publish is as soon as possible. There is that EarCut problem with the current npm version and it might cause some problems with people.

**Comment by photonstorm** [comment]
Ok. In order to publish, the version number in the `package.json` and `src/Phaser.js` files both need updating. Then run `grunt release` so it rebuilds the docs / TS defs and creates the build files.

I don't mind doing the above of course, but I think it makes sense for the community to get used to what's involved.

**Comment by stoneman1** [comment]
Will do that next time. And yeah of course it makes sense for the community to do that 👍

**Comment by photonstorm** [comment]
Oh, you also need to decide if you want versions to have a release name any more too :) It's in the package.json, but it doesn't have to be a name, it could just be a date or something. Up to you all! There's a file in the `resources` folder that contains all of the names I was going to use for versions, and which ones have been used / are left. You can do whatever you want though, but just saying it's there if you want it.

**Pull request merged**
