### PR TITLE
types: complete Phaser.Input.Gamepad.Configs definitions

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Updates the Documentation

Describe the changes below:
complete Phaser.Input.Gamepad.Configs definitions for better autocompletion and better TypeScript developer experience

### CODE REVIEW

**Comment by vforsh** [comment]
> The TS defs are automatically generated from the JSDoc comments found in the Phaser source code. If you wish to help refine them then you must edit the Phaser JSDoc blocks directly, not the defs file. You can find more details about the parser we built in the scripts/tsgen folder.

You shouldn't edit **phaser.d.ts** file directly. To update definitions you should edit JSDoc then run `npm run tsgen`

**Comment by sylvainpolletvillard** [comment]
My bad, I read the contributor's guide but I missed that part in the README. Fixing that soon

**Comment by sylvainpolletvillard** [comment]
@vforsh please review again. I also fixed 2 warnings that tsgen was producing regarding duplicate names

**Comment by photonstorm** [comment]
@sylvainpolletvillard thanks for this PR! Can you please remove the `phaser.d.ts` file from it? Then I can merge it in and release as part of 3.60.

**Comment by sylvainpolletvillard** [comment]
@photonstorm done !

**Comment by photonstorm** [comment]
Thanks :)

**Pull request merged**
