### PR TITLE
In groups, check for child.parent before removeFromHash()

### PR DESCRIPTION
**Pull request by spayton**
Particles are created with arcade physics bodies but have no parent when added to the particle group, so it isn't sufficient to just check child.body we must also check child.parent before calling child.parent.removeFromHash(), otheriwise it crashes.

### CODE REVIEW

**Comment by photonstorm** [comment]
Why would a particle ever be in another Group in order to need removing from its previous hash?

**Comment by spayton** [comment]
Calls to child.parent.removeFromHash() were added in response to issue #2232, I observed that this code could be called when child.parent was undefined causing a crash.

In my case the child was added to the group in Phaser.Particles.Arcade.Emitter.prototype.makeParticles().  At the bottom of this function the new particle being added doesn't have a parent but it does have a body, which are the requirements to subsequently crash.

So, I'm not saying there's particles in other groups being removed from hash, or that there's any problem in particular with the hash - I'm saying it's possible to hit the new code with child.parent == undefined.

**Comment by spayton** [comment]
Just checked again in case it was just my modified phaser build.  On stock dev phaser the problem shows itself on the 1st particles example.

**Comment by photonstorm** [comment]
This is merged locally into dev.

**Pull request closed without merging**
