### PR TITLE
Arcade circles

### PR DESCRIPTION
**Pull request by VitaZheltyakov**
**Important:** Pull Requests should _only_ be issued against the `dev` branch. PRs against the master branch will always be closed.

This PR changes (delete as applicable)

* Nothing, it's a bug fix

Describe the changes below:
 	Added support for circles in various functions

### CODE REVIEW

**Comment by photonstorm** [comment]
Do these work against Tilemaps?

**Comment by VitaZheltyakov** [comment]
No, it does not work.
I have completed a pilot test circles on a tiles. The result is terrible. [examples.zip](https://github.com/photonstorm/phaser/files/301486/examples.zip) See example5
Firstly, it is unclear why it is necessary to process a collision circles with tiles (?). Only the collision of corners will differ from collisions with rectangles.
Secondly, there are so many problems in the processing of collisions on the borders of the tiles. The circle can touch the border of the two tiles. This results in an unnatural behavior.

**Comment by photonstorm** [comment]
Because unless it's guarded against it, I 100% guarantee you that it will generate numerous GitHub issues asking why their circle bodies don't work on a tilemap.

**Comment by VitaZheltyakov** [comment]
You can add support for circles collisions with tiles, but with limitations.
Look at my decision in the archive.

I have not worked and do not work with tiles, so I will not move in that direction.

**Pull request merged**
