### PR TITLE
Fixes #3661

### LINKED ISSUE #366: Phaser.Timer calculates negative tick when started immediately in State#create
Hello,
I stumbled upon this error when testing for another Phaser.Timer related bug. Maybe it is total isolated and not relevant for production but it's easy to reproduce. I digged deep into the main time loop, StateManager and other parts but could not find a place to fix this.

```
var game = new Phaser.Game(800, 600, Phaser.CANVAS, 'phaser-example', {create: create});

function create() {
  //Maybe you have to set it even lower for your machine.
  //It's related to the time Phaser needs to boot up.
  //The tick stops being negative and behaves nearly normal for me at around 550 - 600ms
  delay = 500 
  foreverTimer = game.time.events.repeat(delay, 10, handleEvent, this)
}
function handleEvent(){
  console.log('handleEvent, value of foreverTimer.tick: ', foreverTimer.tick)
}
```

For a delay set to 500 I get the following output nearly immediately (instead of a total of 5000ms).

```
handleEvent, value of foreverTimer.tick:  473.78699999535456 VM1458:11
handleEvent, value of foreverTimer.tick:  340.9409999876516 VM1458:11
handleEvent, value of foreverTimer.tick:  8.369999981368892 VM1458:11
handleEvent, value of foreverTimer.tick:  -673.5060000355588 VM1458:11
handleEvent, value of foreverTimer.tick:  -2048.26700007834 VM1458:11
handleEvent, value of foreverTimer.tick:  -4846.5050001541385 VM1458:11
handleEvent, value of foreverTimer.tick:  -10453.138000302715 VM1458:11
handleEvent, value of foreverTimer.tick:  -21682.57600060315 VM1458:11
handleEvent, value of foreverTimer.tick:  -44158.42500120925 VM1458:11
handleEvent, value of foreverTimer.tick:  -44158.42500120925 
```

I guessed the attribute 'nextTick' have to be set to that duration Phaser needs to boot up- just before starting the game loop. I couldn't find the right place to try this so I only report it for now.

Phaser 1.2 branch
Mac OSX 10.9.1, Chrome 32.0.1700.102
Macbook Air Mid 2013, 1.7Ghz i7

### LINKED ISSUE #3661: Crash when stoping a scene that has a TileSprite inside a container
The following crashes:

```function create() {
  const a = this.add.container(0, 0)
  a.add(new Phaser.GameObjects.Container(this, 0, 0, [
    new Phaser.GameObjects.TileSprite(this, 0, 0, 100, 100, 'logo')
    //new Phaser.GameObjects.Text(this, 0, 0, 'logo')
  ]))
  this.scene.stop('sceneKey')
}
```

with:

```
TileSprite.js:279 Uncaught TypeError: Cannot read property 'gl' of null
    at TileSprite.destroy (TileSprite.js:279)
    at EventEmitter.emit (index.js:202)
    at Systems.shutdown (Systems.js:612)
    at SceneManager.stop (SceneManager.js:1090)
    at ScenePlugin.stop (ScenePlugin.js:618)
    at TotalWarScene.onMessage (TotalWarScene.ts:121)
    at WebSocket.<anonymous> (socketClient.ts:4)
```

But if instead you create the container with the text object that I've attached, it works.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58305957-crash-when-stoping-a-scene-that-has-a-tilesprite-inside-a-container?utm_campaign=plugin&utm_content=tracker%2F283654&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F283654&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by laptou**
This PR

* Fixes a bug

Describe the changes below:

Fixes issue #3661 by checking `this.renderer` for null first.

### CODE REVIEW

**Comment by photonstorm** [comment]
Thank you for this. Could you please fix the eslint error, then we’re good to merge!

**Comment by laptou** [comment]
done

**Comment by laptou** [comment]
By the way, we should probably keep in mind that I didn't try to figure out _why_ `destroy()` is being called twice on TileSprite, I only made it so that the second call is harmless. In case that comes back later.

**Comment by photonstorm** [comment]
Just to say that I'm looking into why this is happening in the first place. Every Game Object has its `destroy` method called twice, not just TileSprites, so I want to fix that rather than band-aid it. Will reference this PR once I'm done investigating.

**Comment by photonstorm** [comment]
Well, that was a chase down a rabbit hole, but finally figured it all out. I don't need to merge this PR now, but will credit you all the same.

**Pull request closed without merging**
