### PR TITLE
With explode=true and quantity=0, emitter.start() wasn't emitting any…

### PR DESCRIPTION
**Pull request by GreatBigBore**
**Important:** Pull Requests should _only_ be issued against the `dev` branch. PRs against the master branch will always be closed.

This PR changes (delete as applicable)

* Nothing, it's a bug fix

Describe the changes below:

emitter.start() with explode = true and no quantity specified, or quantity specified to zero, wasn't emitting anything.

### CODE REVIEW

**Comment by hexus** [comment]
https://github.com/photonstorm/phaser/blob/master/.github/CONTRIBUTING.md#making-changes

Pull requests shouldn't include any build files, just modified source code within `src/`.

**Comment by GreatBigBore** [comment]
Sorry about that. It's my first pull request ever. Should I try a new one, or will you guys just pick up the fix manually? It's less than trivial.

**Comment by hexus** [comment]
No worries! I'm not actually a maintainer, but I checked contribution guidelines before submitting mine earlier today. ;)

I can't actually tell what your change is because the diff is so large:

https://github.com/photonstorm/phaser/pull/2692/files

So perhaps undo this commit on your fork of Phaser and make the change to the source instead, then open a new request. :)

**Comment by photonstorm** [comment]
Hi - thanks for the PR @GreatBigBore - as @hexus said, PRs should be the source files themselves, rather than the build files. The best thing to do would be to close this PR, then open a new one with just the single source file updated (most likely Emitter.js?), then we can merge it into dev and credit it correctly.

**Pull request closed without merging**
