### PR TITLE
Fix path for phaser in the requirejs project template

### PR DESCRIPTION
**Pull request by amcolash**
This PR changes (delete as applicable)
- Nothing, it's a bug fix

Describe the changes below:

Fix the requirejs project template for phaser. Looks like the path changed from "libs/phaser" to "libs/phaser/build/"

I am new to phaser, but just wanted to fix this for others as well!

### CODE REVIEW

**Comment by amcolash** [comment]
Hm, didn't change anything but the path in the project. Looks like something else is breaking the build :disappointed:

**Comment by photonstorm** [comment]
Don't worry about the CI error, that's my fault.

However the line you changed in the requireJS project - it has a comment about it effectively saying "Edit this to whatever you need", i.e. it's a local folder path, not one set by Phaser, so it can be whatever you want. I know some devs like to use a folder called 'vendor' for 3rd party libs, others shove them all in 'js', some in 'libs'. So it's really just an example path, it doesn't have to map to the repo in any way.

**Comment by amcolash** [comment]
I the template should run with no problems if you just do a 'bower
install'. It caught me off guard as I was expecting a fully functional
template (without needing to change the path if you choose to use bower).

**Comment by photonstorm** [comment]
Fair enough. Maybe if you could edit your PR to change the comment to something like "Feel free to edit this path to whatever you like" it will cover both bases, and I can merge it in :)

**Comment by amcolash** [comment]
I added a slightly better comment to the file, looks good to me :)

**Comment by photonstorm** [comment]
Thank you for your PR! Today I released Phaser CE (Community Edition). This is my way of opening up Phaser 2 to the community, allowing you to control features and updates directly. Please see the README in the `v2-community` folder of the repo for more details about this change.

If you could please re-submit your PR against the new Phaser CE version then I will merge it immediately :) Note that PRs now go against the `master` branch, and don't forget to add your change to the README too!

**Pull request closed without merging**
