### PR TITLE
The update method for game objects should be called after the preUpdate.

### PR DESCRIPTION
**Pull request by wtravO**
This PR changes (delete as applicable)

* Nothing, it's a bug fix

Closes Issue #3378 

Describe the changes below:
For extended game objects, the update method is never fired unless the preUpdate is overridden with an update call.  This will ensure it is properly called directly after the preUpdate call in the GameObject.UpdateList.

### CODE REVIEW

**Comment by wtravO** [comment]
@photonstorm Thoughts on this?

**Comment by photonstorm** [comment]
This will conflict with `Group.preUpdate`, which calls the `update` of any children automatically. So some objects could potentially have their `update` called twice per step. I can see what this is trying to do, but I think we need to find a slightly different way to do it.

**Comment by wtravO** [comment]
I see.  Is it necessary that the group call the update methods for its children? As long as all of the preUpdates are ran before any of the updates, it should have the same effect.  The `Group.preUpdate` would simply do the prep and `GameObject.update` would take that prep and apply it automatically.

**Comment by photonstorm** [comment]
As it stands, the problem will be the execution order.  `UpdateList` runs early on, as it's one of the core scene plugins. Clock, Input, Loader and Tweens all update after it. Most the time you'd want `GameObject.update` called _after_ all of the plugins have run their updates. And in some cases, it would be useful to have the GameObjects update before that happened.

More importantly though, I don't want to add every single Game Object to the UpdateList. As it will have to iterate them all, every frame, and in most cases the majority of them won't actually do anything.

I'm happy to remove the `update` call from Group, but we still need a slightly different way to handle it, because I'm not willing to call `update` on every single Game Object created. The Scene emits an `update` event which could be hooked in to. Or we could add a method (or an argument to `setActive`) that inserts it into an UpdateList (and we rename UpdateList to PreUpdateList, as that is actually what it is)

**Comment by wtravO** [comment]
I like the idea of adding an argument to `setActive`.  Seems to be the most unobtrusive way of handling this.  I'll work on that now and revise my PR.  Then we can go from there.

**Comment by wtravO** [comment]
My thoughts are that the `Phaser.GameObjects.UpdateList` is in need of a refactor - considering it does not do any actual updating.  For clarity sake, I'll be referring to the `Phaser.GameObjects.UpdateList` as the `PreUpdateList` henceforth.  

Currently, when `GameObject.setActive(true);` is called, it simply adds a `GameObject` to the `PreUpdateList`.  Perhaps we could add an additional parameter to `GameObject.setActive` that would also inject the `GameObject` into the scenes `UpdateList`.  Just set this parameter to false by default to avoid confusion and over-injection.

**Comment by wtravO** [comment]
This commit was closed due to upcoming alternative approaches to this issue.

**Pull request closed without merging**
