### PR TITLE
Correct type for GameConfig.scene

### LINKED ISSUE #4522: Issue with the Phaser.Types.Core.GameConfig TS definitions in 3.17.0
## Version

* Phaser Version: 3.17.0

* Operating system: not important

* Browser: not important

## Description

My scene's extend from 'Phaser.Scene', but when I updated my project to use 3.17.0 I got the following error in my Phaser.Types.Core.GameConfig object : 
`Type '(typeof IntroScene)[]' is not assignable to type 'Function | Scene | SettingsConfig | CreateSceneFromObjectConfig | Scene[] | SettingsConfig[] | CreateSceneFromObjectConfig[]'.`

Theirs an issue with the type defs for 'Phaser.Types.Core.GameConfig' for scene's that extend from 'Phaser.Scene'.
I had to add the following to the definitions to make my code work again :  `typeof Phaser.Scene | typeof Phaser.Scene[] |`.

### PR DESCRIPTION
**Pull request by samme**
This PR

* Fixes a bug (TypeScript)

Fixes #4522

### CODE REVIEW

**Comment by photonstorm** [comment]
This used to be in there, but I'm sure it stops the TS defs from compiling. Will re-add and check.

**Comment by photonstorm** [comment]
If I add in _just_ this change, the TS defs error with the following:

```
../../../types/phaser.d.ts(48564,246): error TS7014: Function type, which lacks return-type annotation, implicitly has an 'any' return type.
../../../types/phaser.d.ts(48564,246): error TS8020: JSDoc types can only be used inside documentation comments.
```

**Comment by photonstorm** [comment]
Remove the `function[]` part and they compile without error. Hmmm.. ideas anyone?!

**Comment by samme** [comment]
The `function()[]` in the output is incorrect. It should be `Function[]`.

```
47842                 scene?: Phaser.Scene | Phaser.Scene[] | Phaser.Types.Scenes.SettingsConfig | Phaser.Types.Scenes.SettingsConfig[] | Phaser.Types.Scenes.CreateSceneFromObjectConfig | Phaser.Types.Scenes.CreateSceneFromObjectConfig[] | Function | function()[];
                                                                                                                                                                                                                                                           ~~~~~~~~~~
```

**Comment by photonstorm** [comment]
Fixed locally. Phew.

**Pull request closed without merging**
