### PR TITLE
Fix types and begin object TypeDef

### PR DESCRIPTION
**Pull request by orblazer**
This PR changes (delete as applicable)

* Documentation

Describe the changes below:

I have fix some types (like `array`) and begin replace `object` by reference to `@typedef`.

### CODE REVIEW

**Comment by photonstorm** [comment]
Lovely, merged.

I've been getting rid of return types that are in-lined objects and swapping to TypeDefs or actual instances.

Also, please be aware of the case for these: `{Object.<string, any>}` (should be `{object.<string, any>}`.

**Comment by orblazer** [comment]
Ops, the `Object` is wrong :) if you dont have fix this before my next PR i fix that.

**Comment by photonstorm** [comment]
I need to head off for a bit, will carry on later tonight.

**Comment by photonstorm** [comment]
Just to add, I've been using this to check the return types from functions: http://phaser.io/newdocs/3.0.0/types this will bring up a list of all distinct return types, then you can filter down to see what returns them. Handy for figuring out typos, etc :)

**Pull request merged**
