### PR TITLE
Fixed `this` return types

### PR DESCRIPTION
**Pull request by JasonHK**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Fixes a bug

Describe the changes below:

* Fixed `this` return types for `Phaser.Animations.Animation`.
* Fixed `this` return types for `Phaser.Animations.AnimationManager`.
* Fixed `this` return types for `Phaser.Cache.BaseCache`.
* Fixed `this` return types for `Phaser.Cameras.Controls.FixedKeyControl`.
* Fixed `this` return types for `Phaser.Cameras.Controls.SmoothedKeyControl`.
* Fixed `this` return types for `Phaser.Cameras.Scene2D.BaseCamera`.
* Fixed `this` return types for `Phaser.Cameras.Scene2D.Camera`.
* Fixed `this` return types for `Phaser.Cameras.Scene2D.CameraManager`.
* Fixed `this` return types for `Phaser.Curves.Ellipse`.
* Fixed `this` return types for `Phaser.Curves.Path`.
* Fixed `this` return types for `Phaser.Curves.Spline`.
* Fixed `this` return types for `Phaser.Data.DataManager`.
* Fixed `this` return types for `Phaser.Geom.Circle`.
* Fixed `this` return types for `Phaser.Geom.Ellipse`.
* Fixed `this` return types for `Phaser.Geom.Line`.
* Fixed `this` return types for `Phaser.Geom.Point`.
* Fixed `this` return types for `Phaser.Geom.Polygon`.
* Fixed `this` return types for `Phaser.Geom.Rectangle`.
* Fixed `this` return types for `Phaser.Geom.Triangle`.
* Fixed `this` return types for `Phaser.Input.InputPlugin`.
* Fixed `this` return types for `Phaser.Input.Keyboard.Key`.
* Fixed `this` return types for `Phaser.Input.Keyboard.KeyboardPlugin`.
* Fixed `this` return types for `Phaser.Input.Mouse.MouseManager`.
* Fixed `this` return types for `Phaser.Input.Touch.TouchManager`.
* Fixed `this` return types for `Phaser.Plugins.PluginManager`.

### CODE REVIEW

**Comment by hexus** [comment]
Why do you consider this a bug fix when it's a docs update? Does `{this}` really make that much of a difference to type-hinting or is it simply for brevity? Also, why a commit for each file?

**Comment by JasonHK** [comment]
This pull request is similar to #4968, these pull requests fixed the type-hinting issues with TypeScript. Because of this, I consider it to be a bug fixes.

**Comment by hexus** [comment]
Ah, I see why this is important now: specifically for polymorphism: 
https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types

Of course! :nerd_face: Looks great.

**Comment by photonstorm** [comment]
👍

**Pull request merged**
