### PR TITLE
fixed Weapon Plugin's fire(), setBulletBodyOffset doc explanation, as…

### PR DESCRIPTION
**Pull request by JTronLabs**
… well as Body's setSize function

This PR changes (delete as applicable)

* Documentation

Issues touched upon https://github.com/photonstorm/phaser/issues/2693 https://github.com/photonstorm/phaser/issues/2720

### CODE REVIEW

**Comment by JTronLabs** [comment]
Fixed issue https://github.com/photonstorm/phaser/issues/2723 in commit #2

**Comment by JTronLabs** [comment]
Fixed issue https://github.com/photonstorm/phaser/issues/2724 in third commit

**Comment by photonstorm** [comment]
It looks like something (an IDE plugin perhaps?) has updated all of the JSDoc blocks, putting little spaces in, which is making it next to impossible to determine the actual real changes in this PR vs. what looks like a bit of IDE barf?

**Comment by JTronLabs** [comment]
Yeah sorry, I think it was beautified. I'll fix this up and submit a new PR

**Pull request closed without merging**
