### PR TITLE
Add grunt task to generate d.ts with comments

### PR DESCRIPTION
**Pull request by vulvulune**
Add "tsdocs" grunt task to generate d.ts files with comments.

The task does these steps:
1) Generate the pixi-jsdoc.js
2) Execute jsdoc with a specific Template. It generates a json file with the comments structured in the out folder.
3) A script (buildtsdoc) create new d.ts files with comments found in the json file.
4) Replace the pixi.d.ts reference with pixi.comments.d.ts in the phaser.comments.d.ts file

This commit contains the 2 comments.d.ts files generated with the last version of the dev source code.

### CODE REVIEW

**Comment by photonstorm** [comment]
Very nice. I can see you're still pushing changes up to this - let me know when you'd like me to merge it for testing.

**Comment by vulvulune** [comment]
For me you can merge it now. The comments files look fine.

**Comment by photonstorm** [comment]
There we go. @clark-stevenson would you mind checking this is still all ok for you please?

**Comment by clark-stevenson** [comment]
Screen

How good is that?? 

I switched my dev over to this and not a single problem.

@vulvulune this is great!

**Comment by vulvulune** [comment]
Thank you @clark-stevenson for your greetings :-)

Now that I have scripts to generate the comments.d.ts files, I can use them to check the phaser.d.ts file. Can you please have a look about some questions I have here #1557 ? 

I've already fix some little errors in the phaser.d.ts file, I will do a pull request soon.

Thank you

**Pull request merged**
