### PR TITLE
Update typings reference

### LINKED ISSUE #2746: phaser/typescript/typings.json is not a module
This Issue is about (delete as applicable)
- An error in the TypeScript defs

When using `typescript@next` I get `phaser/typescript/typings.json is not a module`. This probably happens because of this line: https://github.com/photonstorm/phaser/blob/master/package.json#L51
I never saw someone linking to the `typings.json`. I think this must be linked to a `.d.ts`.

Other errors I get: `phaser/typescript/typings.json(2,11): error TS1005: ';' expected.`

### PR DESCRIPTION
**Pull request by jamesgroat**
**Important:** Pull Requests should _only_ be issued against the `dev` branch. PRs against the master branch will always be closed.

This PR changes (delete as applicable)
- Nothing, it's a bug fix

Describe the changes below:

Fixes #2746 as suggested by wingyplus.

### CODE REVIEW

**Comment by photonstorm** [comment]
Won't doing this fail to include the p2 and pixi defs though?

**Comment by jamesgroat** [comment]
I think they get pulled in via the 1st 2 lines of the phaser.comments.d.ts:

```
/// <reference path="pixi.comments.d.ts" />
/// <reference path="p2.d.ts" />
```

I pulled my branch via npm and it fixed my import. I'm importing like this: import * as Phaser from 'phaser' and I was able to get a pixi reference to compile as well show up in intellisense: 

`test: PIXI.AbstractFilter;`

However, I am honestly not 100% sure. @wingyplus suggested the original fix and might shed more light.

**Comment by marcus-robinson** [comment]
I've spent several hours this morning trying to get Phaser and Typescript 2.0 to play nicely and I can confirm this pull request is the only way to get Phaser working properly with Typescript 2.0. 

After applying this change, you can import Phaser like this:

`import "phaser";`

And then reference it in your Typescript code like this:

`this.game = new Phaser.Game(800, 600, Phaser.AUTO, 'content', { preload: this.preload, create: this.create });`

References to Pixi and p2 also work with this approach. 

@photonstorm please consider approving this PR - it resolves issue #2746 I'm sure it's the only way forward 👍 

cc @wingyplus

**Comment by marcus-robinson** [comment]
This seems to be the only workaround - add this to the top of every file referencing Phaser:

`/// <reference path="../../node_modules/phaser/typescript/phaser.d.ts"/>`

This way you get type checking, but the Phaser import is not included in the transpiled JS.

**Comment by wingyplus** [comment]
@marcus-robinson with `require` function in module bundler, you can define `"phaser"` as a external dependencies to prevent combine Phaser sources. See [browserify](https://github.com/substack/node-browserify#bexternalfile) for example.

**Comment by photonstorm** [comment]
Thank you for your PR! Today I released Phaser CE (Community Edition). This is my way of opening up Phaser 2 to the community, allowing you to control features and updates directly. Please see the README in the `v2-community` folder of the repo for more details about this change.

If you could please re-submit your PR against the new Phaser CE version then I will merge it immediately :) Note that PRs now go against the `master` branch, and don't forget to add your change to the README too!

**Pull request closed without merging**
