### PR TITLE
Update JSDoc on Input, GameObjects, Animation and Display

### PR DESCRIPTION
**Pull request by orblazer**
This PR changes (delete as applicable)

* Documentation

Describe the changes below:

I have fixe types on `Input`, `GameObjects`, `Animation` and `Display`.
Next: i end types on Matter.JS :)

### CODE REVIEW

**Comment by photonstorm** [comment]
Rats, I had literally just done the Input ones too!! I'll merge yours and then manually merge in mine, because I was replacing `[description]` tags too :)

**Comment by orblazer** [comment]
Ok, sorry :) i don't have replace `[description]` because i don't know if write short descrition is write.

Like this : `The horizontal acceleration` (on my first "Update JSDoc" PR, in [physics/arcade/component/Acceleration#39](https://github.com/photonstorm/phaser/commit/af3c03a3cb1b91ef8c737dc0df5d3bf0a3e38d4a#diff-0ec8f711d16cbd1a5f9efefcb32401a9R39))

Thanks.

**Comment by photonstorm** [comment]
Yeah don't worry, I'm only replacing the `[descriptions]` when they're really short and easy! I've merged in my changes and pushed them up. There were a couple of mistakes for the types I fixed, but nothing massive.

If you're doing Matter now then I'll do the /display/ ones.

Matter will be quite tricky where the objects are Matter objects (like `engine` and `composite`) and outside of the Phaser namespace. Not entirely sure what we should do there.

**Comment by orblazer** [comment]
Ok, i go write short description in GameObjects and after probably Input.

**Comment by photonstorm** [comment]
Don't worry about the descriptions for now. Types are more important (and there aren't many left! woohoo!!)

**Comment by photonstorm** [comment]
Just pushed my changes. Other than Matter that is everything done now I think! I'm now going to write a script to dump out every single data-type into a list, so we can scan it for errors / typos.

**Comment by orblazer** [comment]
Ok, me probably i go soon begin write script for make TypeDefs. This is probably complex for make interface for types object params. We can create `@typedef` for simplify that task.

**Comment by photonstorm** [comment]
If you've done any work on Matter then push that up now and I can finish it off.

I'm happy to swap all 'object' types for TypeDefs, it will make the jsdocs nicer too.

**Comment by orblazer** [comment]
I don't have work on Matter, i work on 'object' types (now in DIsplay)

**Comment by photonstorm** [comment]
Ok no worries, I'll do Matter now then.

**Pull request merged**
