### PR TITLE
Feature: Allow random generator to get/set state

### PR DESCRIPTION
**Pull request by luckylooke**
Discussed here #1900

### CODE REVIEW

**Comment by luckylooke** [comment]
@pnstickne Ok, I will apply your comments.

**Comment by luckylooke** [comment]
@pnstickne please check it if you like it.. I was testing it.. so functionality works correctly. Jshint passed locally, so maybe .jshintrc differs from one used in TravisCI.

**Comment by pnstickne** [comment]
I think it looks pretty good.

Make sure to rebase the commit down if possible.

**Comment by luckylooke** [comment]
Ok I will tomorrow.

**Comment by luckylooke** [comment]
Rebased ;)

**Comment by pnstickne** [comment]
Cool. Don't forget the constructor documentation updates :)

**Comment by luckylooke** [comment]
Ach... ok.. tomorow then.. :)

**Comment by luckylooke** [comment]
@pnstickne Check it please, I was not sure how to describe it.

**Comment by pnstickne** [comment]
Oh, I missed the change. I think that is pretty good.

Could use "..or a generator state (from {#state})" to use documentation linking.

**Comment by luckylooke** [comment]
@pnstickne check please :)

**Comment by pnstickne** [comment]
:+1:

**Comment by luckylooke** [comment]
Hopefully it will be merged at the end. :) Anyway thank you @pnstickne  for mentorship :D I have learnt some useful things from this lecture. :+1:

**Comment by photonstorm** [comment]
Thanks for this, looks quite handy. I need to tidy-up the code a bit, the jsdocs don't quite match what we use and nor does the code style, but you don't need to do another PR, I'll just merge now and fix locally. Thanks!

**Comment by luckylooke** [comment]
Thank you very much Rich! :)

**Pull request merged**
