### PR TITLE
Allow for keys to be numbers

### PR DESCRIPTION
**Pull request by Twilrom**
This PR changes (delete as applicable)

* Nothing, it's a bug fix

Describe the changes below:

Allow for keys to be numbers as well as strings. It will map to a string, but 1 is just so much shorter than '1'

### CODE REVIEW

**Comment by icbat** [comment]
If accepted, it seems like you could also use a bool as your key, or a function, right? Anything that's not explicitly an object?

**Comment by Twilrom** [comment]
Sure. They'd all get converted to a string though.

**Comment by photonstorm** [comment]
It would have to map to an Object property. So using a boolean would get converted into `true` or `false` as the property key. A function equally would work, but the text of the function itself is stored (unless invoked, in which case the return value is), so you'd have to retrieve it using heck of a key:

```
var bob = { x: 0 };
bob[true] = 98
bob[function(){}] = 'hello';
bob[function wibble(){}] = 'hello2';

Object.keys(bob);
(4) ["x", "true", "function (){}", "function wibble(){}"]
```

I mean it's beyond horrendous to look at, but technically it works.

**Comment by photonstorm** [comment]
I'm struggling over this PR. Personally, I don't like the idea of using anything other than strings for keys. There's no reason you'd ever use a purely numeric key, as it doesn't identify anything. It feels like it just encourages lazy behavior.

On the flip-side, there's no reason not to allow it either. It makes no difference technically or performance wise. The only area it adds complexity is to the documentation, although I'd be inclined to not even mention it as a valid datatype to avoid that (and to discourage from actually doing it.)

Going to wait for @bitnenfer review before we decide.

**Comment by Twilrom** [comment]
I'm really just trying to get away from using keys at all. I could maybe do
it in a cleaner way though...

On Sep 26, 2017 17:24, "Richard Davey" <notifications@github.com> wrote:

I'm struggling over this PR. Personally, I don't like the idea of using
anything other than strings for keys. There's no reason you'd ever use a
purely numeric key, as it doesn't identify anything. It feels like it just
encourages lazy behavior.

On the flip-side, there's no reason not to allow it either. It makes no
difference technically or performance wise. The only area it adds
complexity is to the documentation, although I'd be inclined to not even
mention it as a valid datatype to avoid that (and to discourage from
actually doing it.)

Going to wait for @bitnenfer <https://github.com/bitnenfer> review before
we decide.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/photonstorm/phaser/pull/3062#issuecomment-332234606>,
or mute the thread

**Comment by GGAlanSmithee** [comment]
This would also allow for `null` and `undefined` to be set as properties, which could invite some weird bugs.. In general, I guess it's better to whitelist than blacklist, maybe `typeof frames === 'string' || typeof frames === 'number'` ?

**Comment by photonstorm** [comment]
Sorry, closing this one off. Keys should be strings.

**Pull request closed without merging**
