### PR TITLE
add an optional textureData when initialize shader

### PR DESCRIPTION
**Pull request by cristlee**
Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Updates the Documentation
* Adds a new feature
* Fixes a bug

Describe the changes below:

### CODE REVIEW

**Comment by photonstorm** [comment]
Thanks for your PR! I'm happy to merge this, but please could you stop your editor from making all those white-space changes first. Also, you'll need to pull from master and re-apply the change, as the Shader file updated a tiny bit since this PR which causes a merge conflict otherwise.

**Comment by cristlee** [comment]
Done

**Comment by photonstorm** [comment]
Brilliant, thank you. One last small update: Please add in the jsdocs for the Shader constructor as the new parameter is missing from the docblock. Alternatively, post a jsdoc description here and I'll update it.

**Comment by cristlee** [comment]
Thanks, added the parameter in the jsdocs for both the constructor and setShader method

**Comment by cristlee** [comment]
@photonstorm can this or be merged?

**Comment by photonstorm** [comment]
👍

**Pull request merged**
