### PR TITLE
Update state of (mouse) botton in `move` handler

### PR DESCRIPTION
**Pull request by rexrainbow**
This PR (delete as applicable)
* Fixes a bug

Describe the changes below:

Update state of (mouse) botton in `move` handler. #3779

### CODE REVIEW

**Comment by rexrainbow** [comment]
`this.buttons` has been updated in last commit. Please review it.

**Comment by rexrainbow** [comment]
Sorry I add another PR about tween which is not related to issue of mouse event.
(BTW, How to submit multiple PRs?)

**Comment by rexrainbow** [comment]
Here is a new PR, add `Offset`, `OffsetPoint` methods of polygon shape.

**Comment by photonstorm** [comment]
Hi - thanks for this PR, sorry it took a while to get around to it. I have fixed the Pointer.move issue and the Tween returns locally and pushed them to master (as too many changes had occurred since your PR to merge it safely).

I like the look of the two Polygon functions but could you please complete the jsdocs for them? I can't merge without them.

**Pull request closed without merging**
